header_style = { fg = "yellow", bg = "purple", is_bold = true, is_dimmed = true, is_italic = false, is_underline = false, is_blink = false, is_reverse = false, is_hidden = false, is_strikethrough = false }

#comment above
completion_mode = "circular"
edit_mode = "vi" #comment to the right
history_size = 100000
key_timeout = 500
disable_table_indexes = false
header_align = "l"
#header_color = "c"
header_bold = true
nonzero_exit_errors = true
startup = ["alias bc [] {calc}", "alias la [path] {ls --full $path}", "alias tlog [] {TortoiseGitProc /command:log /path:.}", "alias add-alias [alias-string] { config get startup | append $alias-string | config set_into startup }", "alias nudown [] {fetch https://api.github.com/repos/nushell/nushell/releases | get assets | select name download_count}", "alias build-profile [arg1 arg2 arg3] { with-env [RUSTFLAGS '-C debuginfo=2 -C opt-level=0 -C link_args=/PROFILE'] { cargo build $arg1 $arg2 $arg3 }}"]
table_mode = "other"
plugin_dirs = ["D:\\Src\\GitHub\\nu-plugin-lib\\samples\\Nu.Plugin.Len\\bin\\Debug\\netcoreapp3.1"]
pivot_mode = "auto"
ctrlc_exit = false
complete_from_path = true
rm_always_trash = true
use_starship = false
path = ["C:\\WINDOWS\\system32", "C:\\WINDOWS", "C:\\WINDOWS\\System32\\Wbem", "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\", "C:\\WINDOWS\\System32\\OpenSSH\\", "C:\\Program Files\\PowerShell\\7\\", "C:\\Apps\\Git\\cmd", "C:\\Program Files\\dotnet\\", "C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\", "C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\", "C:\\Users\\dschroeder\\.cargo\\bin", "C:\\Users\\dschroeder\\AppData\\Local\\Microsoft\\WindowsApps", "C:\\Users\\dschroeder\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\bin"]
#prompt = "echo [ $(ansi green) $(pwd | split row \"/\" | first $(pwd | split row \"/\" | count | = $it - 1 ) | each { str substring \"0,1\" | format \"{$it}/\" } | append $(pwd | split row \"/\" | last ) | str collect) $(do -i { git rev-parse --abbrev-ref HEAD | trim | echo $(ansi reset) \"(\" $(ansi blue) $it $(ansi reset) \")\" | str collect }) $(ansi reset) \"> \"]"
prompt = "echo [ $(ansi gb) $(pwd) $(ansi reset) \"(\" $(ansi cb) $(do -i { git rev-parse --abbrev-ref HEAD | trim }) $(ansi reset) \")\" $(char newline) $(ansi yb) $(date --format \"%m/%d/%Y %I:%M:%S%.3f %p\" --raw) $(ansi reset) \"> \" ] | str collect"
TestKey = "TestValue"
#prompt = "echo [ $(ansi green) $(pwd | split row \"\\\" | first $(pwd | split row \"\\\" | count | = $it - 1 ) | each { str substring \"0,3\" | format \"{$it}\\\" } | append $(pwd | split row \"\\\" | last ) | str collect) $(do -i { git rev-parse --abbrev-ref HEAD | trim | echo $(ansi reset) \"(\" $(ansi blue) $it $(ansi reset) \")\" | str collect }) $(ansi reset) \"> \"]"

#These, in the rustyline section are not implemeted yet
[rustyline]
max_history_size = 100000
history_duplicates = "alwaysadd"
history_ignore_space = true
completion_type = "circular"
completion_prompt_limit = 1
keyseq_timeout = 500
edit_mode = "vi"
auto_add_history = true
bell_style = "audible"
color_mode = "enable"
tab_stop = 4

[textview]
term_width = "default"
tab_width = 4
colored_output = true
true_color = true
header = true
line_numbers = true
grid = false
vcs_modification_markers = true
snip = true
wrapping_mode = "NoWrapping"
use_italics = true
paging_mode = "QuitIfOneScreen"
pager = "less"
theme = "TwoDark"

[env]
ALLUSERSPROFILE = "C:\\ProgramData"
APPDATA = "C:\\Users\\dschroeder\\AppData\\Roaming"
CommonProgramFiles = "C:\\Program Files\\Common Files"
"CommonProgramFiles(x86)" = "C:\\Program Files (x86)\\Common Files"
CommonProgramW6432 = "C:\\Program Files\\Common Files"
COMPUTERNAME = "DSCHROLENOVO"
ComSpec = "C:\\WINDOWS\\system32\\cmd.exe"
DEFLOGDIR = "C:\\ProgramData\\McAfee\\DesktopProtection"
DriverData = "C:\\Windows\\System32\\Drivers\\DriverData"
HOMEDRIVE = "C:"
HOMEPATH = "\\Users\\dschroeder"
LOCALAPPDATA = "C:\\Users\\dschroeder\\AppData\\Local"
LOGONSERVER = "\\\\DSCHROLENOVO"
NUMBER_OF_PROCESSORS = "16"
NVIDIAWHITELISTED = "0x01"
OneDrive = "C:\\Users\\dschroeder\\OneDrive"
OneDriveConsumer = "C:\\Users\\dschroeder\\OneDrive"
OS = "Windows_NT"
PATHEXT = ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC"
POWERSHELL_DISTRIBUTION_CHANNEL = "MSI:Windows 10 Pro"
PROCESSOR_ARCHITECTURE = "AMD64"
PROCESSOR_IDENTIFIER = "Intel64 Family 6 Model 158 Stepping 13, GenuineIntel"
PROCESSOR_LEVEL = "6"
PROCESSOR_REVISION = "9e0d"
ProgramData = "C:\\ProgramData"
ProgramFiles = "C:\\Program Files"
"ProgramFiles(x86)" = "C:\\Program Files (x86)"
ProgramW6432 = "C:\\Program Files"
PSModulePath = "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules"
PUBLIC = "C:\\Users\\Public"
SHIM_MCCOMPAT = "0x810000001"
SystemDrive = "C:"
SystemRoot = "C:\\WINDOWS"
TEMP = "C:\\Users\\DSCHRO~1\\AppData\\Local\\Temp"
TMP = "C:\\Users\\DSCHRO~1\\AppData\\Local\\Temp"
USERDOMAIN = "DSCHROLENOVO"
USERDOMAIN_ROAMINGPROFILE = "DSCHROLENOVO"
USERNAME = "dschroeder"
USERPROFILE = "C:\\Users\\dschroeder"
VSEDEFLOGDIR = "C:\\ProgramData\\McAfee\\DesktopProtection"
windir = "C:\\WINDOWS"
WSLENV = "WT_SESSION::WT_PROFILE_ID"
WT_PROFILE_ID = "{2b372ca1-1ee2-403d-a839-6d63077ad871}"
WT_SESSION = "be48c19c-65bb-45d5-94e0-678e3088f7c0"
